//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/CampusBookingSystemJS")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        void AddBook(LibraryConsole.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(LibraryConsole.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        void UpdateBook(LibraryConsole.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(LibraryConsole.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        void DeleteBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBook", ReplyAction="http://tempuri.org/IService1/GetBookResponse")]
        LibraryConsole.ServiceReference1.Book GetBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBook", ReplyAction="http://tempuri.org/IService1/GetBookResponse")]
        System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book> GetBookAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBooks", ReplyAction="http://tempuri.org/IService1/GetAllBooksResponse")]
        LibraryConsole.ServiceReference1.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBooks", ReplyAction="http://tempuri.org/IService1/GetAllBooksResponse")]
        System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByTitle", ReplyAction="http://tempuri.org/IService1/SearchByTitleResponse")]
        LibraryConsole.ServiceReference1.Book[] SearchByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByTitle", ReplyAction="http://tempuri.org/IService1/SearchByTitleResponse")]
        System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> SearchByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByAuthor", ReplyAction="http://tempuri.org/IService1/SearchByAuthorResponse")]
        LibraryConsole.ServiceReference1.Book[] SearchByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByAuthor", ReplyAction="http://tempuri.org/IService1/SearchByAuthorResponse")]
        System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> SearchByAuthorAsync(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByISBN", ReplyAction="http://tempuri.org/IService1/SearchByISBNResponse")]
        LibraryConsole.ServiceReference1.Book SearchByISBN(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchByISBN", ReplyAction="http://tempuri.org/IService1/SearchByISBNResponse")]
        System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book> SearchByISBNAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckBookAvailability", ReplyAction="http://tempuri.org/IService1/CheckBookAvailabilityResponse")]
        bool CheckBookAvailability(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckBookAvailability", ReplyAction="http://tempuri.org/IService1/CheckBookAvailabilityResponse")]
        System.Threading.Tasks.Task<bool> CheckBookAvailabilityAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckOutBook", ReplyAction="http://tempuri.org/IService1/CheckOutBookResponse")]
        void CheckOutBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckOutBook", ReplyAction="http://tempuri.org/IService1/CheckOutBookResponse")]
        System.Threading.Tasks.Task CheckOutBookAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        void ReturnBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        System.Threading.Tasks.Task ReturnBookAsync(int bookID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LibraryConsole.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LibraryConsole.ServiceReference1.IService1>, LibraryConsole.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(LibraryConsole.ServiceReference1.Book book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(LibraryConsole.ServiceReference1.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void UpdateBook(LibraryConsole.ServiceReference1.Book book) {
            base.Channel.UpdateBook(book);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(LibraryConsole.ServiceReference1.Book book) {
            return base.Channel.UpdateBookAsync(book);
        }
        
        public void DeleteBook(int bookID) {
            base.Channel.DeleteBook(bookID);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(int bookID) {
            return base.Channel.DeleteBookAsync(bookID);
        }
        
        public LibraryConsole.ServiceReference1.Book GetBook(int bookID) {
            return base.Channel.GetBook(bookID);
        }
        
        public System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book> GetBookAsync(int bookID) {
            return base.Channel.GetBookAsync(bookID);
        }
        
        public LibraryConsole.ServiceReference1.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public LibraryConsole.ServiceReference1.Book[] SearchByTitle(string title) {
            return base.Channel.SearchByTitle(title);
        }
        
        public System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> SearchByTitleAsync(string title) {
            return base.Channel.SearchByTitleAsync(title);
        }
        
        public LibraryConsole.ServiceReference1.Book[] SearchByAuthor(string author) {
            return base.Channel.SearchByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book[]> SearchByAuthorAsync(string author) {
            return base.Channel.SearchByAuthorAsync(author);
        }
        
        public LibraryConsole.ServiceReference1.Book SearchByISBN(string isbn) {
            return base.Channel.SearchByISBN(isbn);
        }
        
        public System.Threading.Tasks.Task<LibraryConsole.ServiceReference1.Book> SearchByISBNAsync(string isbn) {
            return base.Channel.SearchByISBNAsync(isbn);
        }
        
        public bool CheckBookAvailability(int bookID) {
            return base.Channel.CheckBookAvailability(bookID);
        }
        
        public System.Threading.Tasks.Task<bool> CheckBookAvailabilityAsync(int bookID) {
            return base.Channel.CheckBookAvailabilityAsync(bookID);
        }
        
        public void CheckOutBook(int bookID) {
            base.Channel.CheckOutBook(bookID);
        }
        
        public System.Threading.Tasks.Task CheckOutBookAsync(int bookID) {
            return base.Channel.CheckOutBookAsync(bookID);
        }
        
        public void ReturnBook(int bookID) {
            base.Channel.ReturnBook(bookID);
        }
        
        public System.Threading.Tasks.Task ReturnBookAsync(int bookID) {
            return base.Channel.ReturnBookAsync(bookID);
        }
    }
}
